(() => {
  if (window.__yatAudienceSite) return;
  window.__yatAudienceSite = true;

  const PLATFORM = 'https://hamilton.az.yatstats.com';
  const CODY = `${PLATFORM}/5004/player/180827/cody-bellinger`;
  const CARD = `${PLATFORM}/?view=active&player=180827#player-180827`;
  const S3 = 'https://yatstats-assets.s3.us-west-2.amazonaws.com';
  const LOGO = 'https://yatstats.github.io/hamilton-mvp/assets/img/yatstats-logo.png';
  const YATI = `${S3}/yatstats/YaTi.png`;
  const BG = `${PLATFORM}/img/career-path-default.png`;
  const CODY_CUTOUT = `${S3}/players/cutouts/180827.png`;

  const shared = {
    search: {label:'Search', type:'yati', kicker:'Find anybody, from anywhere', title:'Search by player, high school, or the team he plays for now.', copy:'Global Search crosses every YAT?STATS community and takes the visitor back to the hometown program behind each player.', url:PLATFORM, callout:'GLOBAL SEARCH', x:91, y:8},
    cards: {label:'Flip Cards', type:'player', kicker:'Past on the front. Present on the back.', title:'Every alumni card has another side.', copy:'The front preserves the high-school identity. Flip it to see the current team, status and recent production.', url:CARD, callout:'TAP / FLIP A PLAYER CARD', x:22, y:44},
    profile: {label:'Player Profile', type:'player', kicker:'The full journey in one place', title:'Open the profile for schedules, stats, news and the Golden Timeline.', copy:'The current chapter remains attached to the hometown story instead of being scattered across unrelated sites.', url:CODY, callout:'OPEN THE PLAYER PROFILE', x:22, y:44},
    timeline: {label:'Golden Timeline', type:'player', kicker:'Past and present on one career line', title:'Stats show what happened. Memories preserve why it mattered.', copy:'Youth ball, high school, college, professional baseball and fan-contributed memories belong on one continuous journey.', url:`${CODY}#playerCareerImages`, callout:'THE GOLDEN TIMELINE', x:36, y:35},
    contribute: {label:'Contribute', type:'yati', kicker:'The people who were there can add the missing chapters', title:'Fans, families, coaches and teammates can contribute photos and memories.', copy:'Add the approximate date and context so each moment lands in the right place on the player’s journey.', url:`${CODY}#ppTab-upload`, callout:'ADD A MEMORY', x:50, y:58}
  };

  const pages = {
    fans: {
      nav:'Fans', eyebrow:'For fans, families and hometown baseball people', title:'YAT?STATS for Fans',
      stops:[
        {label:'Why YAT?STATS',type:'player',kicker:'The hometown never stopped caring',title:'A baseball player’s journey does not end at graduation. Neither should his story.',copy:'Follow the high-school players you still care about through college and professional baseball.',url:PLATFORM,callout:'THE HOMETOWN IS THE ANCHOR',x:18,y:18},
        {label:'Home School',type:'yati',kicker:'Where your fan identity begins',title:'The school community where you join becomes your Home School.',copy:'A Fan can favorite players from that school. A Super Fan can build one cross-school gallery from favorites everywhere.',url:PLATFORM,callout:'JOIN FROM YOUR HOME SCHOOL',x:84,y:14},
        shared.search,shared.cards,shared.profile,
        {label:'Favorite / Super Fan',type:'yati',kicker:'Only the players you care about',title:'Favorite Home School players—or upgrade to build a cross-school gallery.',copy:'Super Fan groups favorited players from different high schools into one custom flip-card experience.',url:PLATFORM,callout:'FAVORITE A PLAYER',x:93,y:14},
        shared.timeline,shared.contribute
      ]
    },
    players: {
      nav:'Active Players', eyebrow:'For college and professional players', title:'YAT?STATS for Active Players',
      stops:[
        {label:'Your Journey',type:'player',kicker:'The hometown still follows',title:'Your story should stay connected to where it started.',copy:'Give former coaches, teammates, family and hometown fans one reliable place to follow the next chapter.',url:CODY,callout:'YOUR COMPLETE PROFILE',x:50,y:16},
        shared.cards,shared.profile,
        {label:'Stats + News',type:'player',kicker:'What are you doing now?',title:'Current production and current news remain easy for hometown fans to find.',copy:'Schedules, stats, milestones and updates stay connected to the high-school community that knew you first.',url:`${CODY}#ppTab-stats`,callout:'CURRENT STATS',x:50,y:76},
        shared.timeline,
        {label:'Stay Connected',type:'yati',kicker:'Your program relationship does not expire',title:'Remain part of the program long after graduation.',copy:'The wider ecosystem can create mentorship, NIL, appearance, career and business opportunities around that continuing relationship.',url:PLATFORM,callout:'YOUR HOME SCHOOL',x:16,y:18}
      ]
    },
    programs: {
      nav:'High School Programs', eyebrow:'For coaches, boosters and program leaders', title:'YAT?STATS for High School Programs',
      stops:[
        {label:'The Question',type:'yati',kicker:'Where are our guys now?',title:'Stop hunting and pecking to track former players.',copy:'YAT?STATS organizes active alumni around the high-school program that developed them.',url:PLATFORM,callout:'YOUR ACTIVE ALUMNI',x:16,y:18},
        {label:'Your Clubhouse',type:'player',kicker:'One branded digital home',title:'Give the program a living alumni clubhouse.',copy:'Current players, alumni, families and fans can see the program’s next-level success in one school-branded environment.',url:PLATFORM,callout:'YOUR SCHOOL COMMUNITY',x:16,y:18},
        {label:'Program History',type:'yati',kicker:'Active and all-time alumni',title:'Recognize every generation—not only the stars still playing.',copy:'Current stats create traffic. All-time history, stories and memories create a lasting community.',url:PLATFORM,callout:'ALL-TIME LIST',x:44,y:8},
        {label:'ARMS',type:'yati',kicker:'Alumni Relationship Management System',title:'Turn anonymous attention into known alumni, parents, families and fans.',copy:'ARMS captures relationships and automates relevant follow-up without creating another manual job for the coaching staff.',url:PLATFORM,callout:'CONNECT THE COMMUNITY',x:72,y:9},
        {label:'Fundraising',type:'yati',kicker:'A larger, warmer support base',title:'Reconnect the people most likely to care about the program.',copy:'Alumni nostalgia, family pride and current-player stories create better reasons to give than a cold fundraising request.',url:PLATFORM,callout:'FUND THE PROGRAM',x:82,y:12},
        {label:'Sponsors',type:'yati',kicker:'Local support with visible value',title:'Offer businesses a better partnership than a forgotten banner.',copy:'Sponsors can fund the clubhouse while receiving meaningful exposure around people and stories the town already values.',url:PLATFORM,callout:'LOCAL PARTNER PROGRAM',x:76,y:9}
      ]
    },
    partners: {
      nav:'Local Business Owners', eyebrow:'For sponsors, partners and investors', title:'YAT?STATS for Local Business Owners',
      stops:[
        {label:'Why It Works',type:'yati',kicker:'Nostalgia creates attention and trust',title:'Local baseball already has an audience that cares.',copy:'YAT?STATS organizes that audience around hometown identity, familiar names and stories people feel personally connected to.',url:PLATFORM,callout:'HOMETOWN ATTENTION',x:18,y:18},
        {label:'Sponsor a School',type:'yati',kicker:'Fund a digital clubhouse',title:'Help make YAT?STATS available to a local program.',copy:'A business can underwrite the platform while becoming visibly associated with the school, its alumni and its families.',url:PLATFORM,callout:'SPONSOR THE CLUBHOUSE',x:76,y:9},
        {label:'Brand Alignment',type:'player',kicker:'Borrowed trust, earned locally',title:'Align your business with a school brand the community already supports.',copy:'The relationship is stronger than generic advertising because it appears inside a meaningful hometown experience.',url:PLATFORM,callout:'COMMUNITY BRAND ALIGNMENT',x:16,y:18},
        {label:'Relevant Exposure',type:'player',kicker:'Show up around stories people choose to follow',title:'Receive visibility beside players, milestones, memories and history.',copy:'Sponsors become part of the experience instead of interrupting it with unrelated advertising.',url:PLATFORM,callout:'SPONSOR VISIBILITY',x:50,y:88},
        {label:'ARMS + Leads',type:'yati',kicker:'Turn attention into relationships',title:'Connect sponsorship exposure to measurable local engagement.',copy:'Lead capture, follow-up and attribution can move a partner beyond passive logo placement.',url:PLATFORM,callout:'ARMS RELATIONSHIP SYSTEM',x:72,y:9},
        {label:'Scale',type:'yati',kicker:'One hometown at a time',title:'The model can repeat across thousands of baseball communities.',copy:'Local sponsors create a scalable network of funded school communities, each rooted in its own history and relationships.',url:PLATFORM,callout:'17,000+ PROGRAMS',x:50,y:16}
      ]
    }
  };

  const key = pages[document.body.dataset.audience] ? document.body.dataset.audience : 'fans';
  const page = pages[key];
  const devices = {desktop:{label:'Desktop',w:1500,h:720},tablet:{label:'Tablet',w:1024,h:768},mobile:{label:'Mobile',w:390,h:844}};
  const reduced = matchMedia?.('(prefers-reduced-motion: reduce)')?.matches;

  const style = document.createElement('style');
  style.textContent = `
  @import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Oswald:wght@300;400;500;600;700&display=swap');
  @font-face{font-family:Indigo;src:url('${PLATFORM}/fonts/Indigo.otf') format('opentype');font-display:swap}
  :root{--bg:#050607;--panel:#0d0f10;--line:#292d31;--text:#f3f3f1;--muted:#9ca0a5;--gold:#c8a96e;--hh:46px;--story:226px}*{box-sizing:border-box}
  html,body{height:100%;margin:0;background:var(--bg);color:var(--text);font-family:Oswald,sans-serif}button,a{font:inherit}a{color:inherit}.app{position:relative;min-height:100dvh;display:flex;flex-direction:column;background:radial-gradient(circle at 75% -10%,rgba(200,169,110,.08),transparent 28%),var(--bg)}
  header{position:absolute;left:0;right:0;top:0;height:var(--hh);flex:none;display:flex;align-items:center;background:linear-gradient(180deg,rgba(3,4,5,.72),rgba(3,4,5,.32) 65%,transparent);z-index:20;pointer-events:none}.head{width:calc(100% - 28px);margin:auto;display:flex;align-items:center;justify-content:space-between;gap:20px;pointer-events:auto}.logo img{display:block;width:132px}.nav{display:flex;gap:clamp(14px,2vw,34px)}.nav a{position:relative;padding:16px 0 14px;text-decoration:none;text-transform:uppercase;white-space:nowrap;color:#eee;opacity:.72;font:400 clamp(10px,.82vw,14px)/1 Indigo,'Bebas Neue',Oswald;text-shadow:0 1px 3px rgba(0,0,0,.6)}.nav a.active,.nav a:hover{opacity:1}.nav a.active:after{content:'';position:absolute;left:0;right:0;bottom:7px;height:2px;background:var(--gold)}.menu{display:none;border:0;background:none;color:#fff;font-size:21px}
  main{flex:1;min-height:0;display:flex;flex-direction:column;width:calc(100% - 18px);margin:auto;padding:0 0 8px}.story{position:relative;flex:0 0 var(--story);border:1px solid var(--line);border-radius:8px 8px 0 0;overflow:hidden;background:#0a0b0c}.track{height:100%;display:flex;overflow-x:auto;overflow-y:hidden;scroll-snap-type:x mandatory;scrollbar-width:none;touch-action:pan-x}.track::-webkit-scrollbar{display:none}.slide{flex:0 0 100%;height:100%;display:grid;grid-template-columns:clamp(300px,29vw,430px) minmax(0,1fr);scroll-snap-align:start;background:linear-gradient(135deg,#111315,#090a0b)}.visual{position:relative;overflow:hidden;border-right:1px solid var(--line);background:#25302d}.bg{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:brightness(.88) saturate(.95)}.person{position:absolute;z-index:2;left:0;bottom:-2%;width:55%;height:103%;object-fit:contain;object-position:left bottom;filter:drop-shadow(0 16px 22px rgba(0,0,0,.36))}.person.yati{left:8%;bottom:-4%;width:48%;height:96%;object-position:center bottom}.visual:after{content:'';position:absolute;z-index:3;inset:0;background:linear-gradient(90deg,rgba(0,0,0,.06),transparent 50%,rgba(0,0,0,.25)),linear-gradient(180deg,transparent 62%,rgba(0,0,0,.58))}.aud{position:absolute;z-index:4;left:13px;top:12px;padding:5px 8px;border:1px solid rgba(255,255,255,.2);border-radius:999px;background:rgba(4,5,6,.62);font:500 8px/1 Oswald;letter-spacing:.12em;text-transform:uppercase}.cap{position:absolute;z-index:4;left:13px;bottom:11px;font:400 8px/1 Oswald;letter-spacing:.1em;text-transform:uppercase}.copy{position:relative;display:flex;flex-direction:column;justify-content:center;padding:24px clamp(58px,5vw,90px) 35px clamp(28px,4vw,64px);background:radial-gradient(circle at 82% 8%,rgba(200,169,110,.10),transparent 32%)}.kick{margin-bottom:7px;color:#dfbf73;font:500 9px/1 Oswald;letter-spacing:.13em;text-transform:uppercase}.title{max-width:940px;margin:0 0 8px;font:400 clamp(30px,3vw,50px)/.96 'Bebas Neue',Oswald;text-transform:uppercase}.bodycopy{max-width:900px;margin:0;color:#a5a8ac;font:300 clamp(11px,.82vw,14px)/1.45 Oswald}.step{position:absolute;right:20px;top:18px;color:#74797f;font:400 9px/1 Oswald;letter-spacing:.1em}.step b{color:#dfbf73;font-size:14px;font-weight:500}.arrows{position:absolute;z-index:8;right:16px;bottom:14px;display:flex;gap:6px}.arrows button{width:34px;height:31px;border:1px solid #3a3f45;border-radius:5px;background:rgba(10,12,13,.84);color:#aaa;cursor:pointer}.progress{position:absolute;z-index:8;left:calc(clamp(300px,29vw,430px) + 28px);right:90px;bottom:13px;display:flex;gap:5px}.progress button{height:3px;flex:1;border:0;padding:0;background:#30343a;cursor:pointer}.progress button.active{background:var(--gold)}
  .live{flex:1;min-height:0;display:grid;grid-template-rows:36px minmax(0,1fr) 21px;border:1px solid var(--line);border-top:0;border-radius:0 0 8px 8px;overflow:hidden;background:#050505}.bar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:4px 8px 4px 12px;border-bottom:1px solid var(--line);background:#0d0f10}.address{display:flex;align-items:center;gap:8px;min-width:0;color:#74797f;font:400 9px/1 Oswald;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.address strong{color:#ddd}.dots{display:flex;gap:4px}.dots i{width:6px;height:6px;border-radius:50%;background:#41464b}.dots i:nth-child(2){background:#755b24}.dots i:nth-child(3){background:#6f2630}.devices{display:flex;align-items:center;gap:5px}.devices button,.open{min-height:26px;padding:0 9px;border:1px solid #33383d;border-radius:5px;background:#151719;color:#a5a9ae;text-decoration:none;cursor:pointer;font:500 9px/1 Oswald;text-transform:uppercase}.devices button.active{border-color:var(--gold);color:#dfbf73;background:rgba(200,169,110,.08)}.wrap{position:relative;min-height:0;overflow:hidden;background:radial-gradient(circle at 50% 40%,#15191c,#020303 72%)}.stage{position:absolute;left:50%;top:50%;transform-origin:center;background:#fff;box-shadow:0 0 0 1px rgba(255,255,255,.08),0 20px 55px rgba(0,0,0,.42);overflow:hidden}.frame{position:absolute;inset:0;width:100%;height:100%;border:0;background:#fff}.loader{position:absolute;z-index:5;inset:0;display:grid;place-items:center;background:#070809;color:#8b9095;font:500 9px/1.4 Oswald;text-transform:uppercase;transition:opacity .2s}.loader.hidden{opacity:0;pointer-events:none}.callout{position:absolute;z-index:6;left:var(--x,50%);top:var(--y,20%);transform:translate(-50%,-50%);pointer-events:none}.dot{width:14px;height:14px;border:2px solid #0a0b0c;border-radius:50%;background:#d5aa40;box-shadow:0 0 0 6px rgba(213,170,64,.22)}.label{position:absolute;left:21px;top:50%;transform:translateY(-50%);white-space:nowrap;padding:5px 7px;border:1px solid rgba(200,169,110,.55);border-radius:5px;background:rgba(5,6,7,.91);color:#dfbf73;font:500 7px/1 Oswald;text-transform:uppercase}.foot{display:flex;align-items:center;justify-content:space-between;padding:3px 9px;border-top:1px solid var(--line);background:#0d0f10;color:#6f7479;font:400 8px/1 Oswald}.foot strong{color:#b6b9bc}
  @media(max-width:900px){html,body{overflow:auto}.app{height:auto;min-height:100dvh}.menu{display:block}.nav{display:none;position:absolute;left:0;right:0;top:var(--hh);padding:12px 16px 18px;background:#050607;border-bottom:1px solid var(--line);flex-direction:column}.nav.open{display:flex}.nav a{padding:10px 0}main{width:100%;padding:0}.story{height:286px;flex-basis:286px;border-radius:0}.slide{grid-template-columns:38% 62%}.copy{padding:20px 22px 34px}.title{font-size:28px}.bodycopy{font-size:10.5px}.progress{left:calc(38% + 20px)}.live{min-height:calc(100dvh - 286px);border-radius:0}.open{display:none}}
  @media(max-width:620px){:root{--hh:42px}.head{width:calc(100% - 18px)}.logo img{width:116px}.story{height:310px;flex-basis:310px}.slide{grid-template-columns:1fr}.visual{height:126px;border-right:0;border-bottom:1px solid var(--line)}.copy{justify-content:flex-start;padding:16px 16px 38px}.title{font-size:25px}.bodycopy{font-size:10px}.step{top:142px;right:13px}.progress{left:16px;right:86px}.person{width:38%;height:110%}.person.yati{width:34%}.live{min-height:calc(100dvh - 310px)}.address{font-size:8px}.devices button{padding:0 6px;font-size:8px}.foot span:last-child{display:none}}
  `;
  document.head.appendChild(style);
  document.title = page.title;

  document.body.innerHTML = `<div class="app"><header><div class="head"><a class="logo" href="/sites/yatstats/fans/"><img src="${LOGO}" alt="YAT?STATS"></a><button class="menu" id="menu">☰</button><nav class="nav" id="nav">${Object.entries(pages).map(([k,p])=>`<a href="/sites/yatstats/${k}/" class="${k===key?'active':''}">${p.nav}</a>`).join('')}</nav></div></header><main><section class="story"><div class="track" id="track">${page.stops.map((s,i)=>`<article class="slide"><div class="visual"><img class="bg" src="${BG}" alt=""><img class="person ${s.type==='yati'?'yati':''}" src="${s.type==='yati'?YATI:CODY_CUTOUT}" alt=""><span class="cap">${s.label}</span></div><div class="copy"><span class="kick">${s.kicker}</span><h1 class="title">${s.title}</h1><p class="bodycopy">${s.copy}</p><span class="step"><b>${String(i+1).padStart(2,'0')}</b> / ${String(page.stops.length).padStart(2,'0')}</span></div></article>`).join('')}</div><div class="progress">${page.stops.map((s,i)=>`<button data-i="${i}" class="${i===0?'active':''}"></button>`).join('')}</div><div class="arrows"><button id="prev">‹</button><button id="next">›</button></div></section><section class="live"><div class="bar"><div class="address"><span class="dots"><i></i><i></i><i></i></span><strong>LIVE YAT?STATS</strong><span id="url">hamilton.az.yatstats.com</span></div><div class="devices"><button data-device="desktop" class="active">Desktop</button><button data-device="tablet">Tablet</button><button data-device="mobile">Mobile</button><a class="open" id="open" href="${PLATFORM}" target="_blank">Open full site ↗</a></div></div><div class="wrap" id="wrap"><div class="stage" id="stage"><div class="loader" id="loader">Loading live Hamilton community</div><iframe class="frame" id="frame" src="${PLATFORM}"></iframe><div class="callout" id="callout"><div class="dot"></div><div class="label" id="label"></div></div></div></div><div class="foot"><span><strong>LIVE PLATFORM:</strong> interact with the real Hamilton subdomain.</span><span>Switch Desktop · Tablet · Mobile to test the responsive experience.</span></div></section></main></div>`;

  const nav=document.getElementById('nav'),menu=document.getElementById('menu');menu.onclick=()=>nav.classList.toggle('open');
  const track=document.getElementById('track'),slides=[...track.children],dots=[...document.querySelectorAll('.progress button')],frame=document.getElementById('frame'),loader=document.getElementById('loader'),url=document.getElementById('url'),open=document.getElementById('open'),callout=document.getElementById('callout'),label=document.getElementById('label'),wrap=document.getElementById('wrap'),stage=document.getElementById('stage');
  let active=0,device='desktop',last='',timer;
  function fit(){const d=devices[device],w=Math.max(1,wrap.clientWidth-20),h=Math.max(1,wrap.clientHeight-14),s=Math.min(1,w/d.w,h/d.h);stage.style.width=d.w+'px';stage.style.height=d.h+'px';stage.style.transform=`translate(-50%,-50%) scale(${s})`}
  function go(i,scroll=true){active=Math.max(0,Math.min(page.stops.length-1,i));const s=page.stops[active];dots.forEach((d,n)=>d.classList.toggle('active',n===active));label.textContent=s.callout;callout.style.setProperty('--x',(s.x||50)+'%');callout.style.setProperty('--y',(s.y||20)+'%');open.href=s.url;try{const u=new URL(s.url);url.textContent=u.hostname+(u.pathname==='/'?'':u.pathname)+(u.hash||'')}catch{}if(last!==s.url){last=s.url;loader.classList.remove('hidden');frame.src=s.url}if(scroll)slides[active].scrollIntoView({behavior:reduced?'auto':'smooth',inline:'start',block:'nearest'})}
  track.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(()=>{const i=Math.round(track.scrollLeft/Math.max(1,track.clientWidth));if(i!==active)go(i,false)},90)},{passive:true});
  track.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();track.scrollLeft+=e.deltaY}},{passive:false});
  document.getElementById('prev').onclick=()=>go((active-1+page.stops.length)%page.stops.length);document.getElementById('next').onclick=()=>go((active+1)%page.stops.length);dots.forEach(d=>d.onclick=()=>go(Number(d.dataset.i)));
  document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{device=b.dataset.device;document.querySelectorAll('[data-device]').forEach(x=>x.classList.toggle('active',x===b));fit()});
  frame.addEventListener('load',()=>{loader.classList.add('hidden');fit()});addEventListener('resize',fit,{passive:true});if('ResizeObserver'in window)new ResizeObserver(fit).observe(wrap);go(0,false);fit();
})();